### ISSUE TITLE
Predict.py

### ISSUE THREAD

**Issue by rishabh-karmakar** [sbhusal123/Speaker-Recognition-Digital-Attendance#1]
Predict.py doesnt give any output. Rather it just shows as sucessfully executed.

**Comment by sbhusal123** [comment]
Hello @Insoler thank you for showing interest on my work.

I've updated the code so that one can predict  specific audio file using:
``python predict.py <audio_file_name>``

Make sure to add the audio file to the dataset/predict folder.

**Comment by rishabh-karmakar** [comment]
Yeah, it's working great now. Thanks a lot, @sbhusal123 .
